#!/bin/bash
# Nginx Abuse Shield - Modular Installer & Updater

set -e

# --- Constants ---
INSTALL_DIR="/usr/local/bin/nginx-abuse-shield"
CONFIG_DIR="/etc/nginx/abuse_shield"
DEST_CONF_FILE="$CONFIG_DIR/abuse_shield.conf"
CRON_FILE="/etc/cron.d/nginx_abuse_shield"
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_CONF_FILE="$SOURCE_DIR/abuse_shield.conf"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Starting Nginx Abuse Shield Installer...${NC}"

# 1. Check Root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root.${NC}"
   exit 1
fi

# 2. Check for source scripts
if [[ ! -f "$SOURCE_DIR/range_checker.sh" ]] || [[ ! -f "$SOURCE_DIR/save_offending_ips.sh" ]]; then
    echo -e "${RED}Error: Source scripts (range_checker.sh, save_offending_ips.sh) not found in $SOURCE_DIR.${NC}"
    exit 1
fi

# 3. Create Directories
echo "Creating directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"

# 4. Install/Update Scripts
echo "Installing scripts to $INSTALL_DIR..."
cp "$SOURCE_DIR/range_checker.sh" "$INSTALL_DIR/"
cp "$SOURCE_DIR/save_offending_ips.sh" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/range_checker.sh"
chmod +x "$INSTALL_DIR/save_offending_ips.sh"
echo -e "${GREEN}Scripts updated.${NC}"

# 5. Configuration Setup
if [ -f "$DEST_CONF_FILE" ]; then
    echo -e "${YELLOW}Configuration file found at $DEST_CONF_FILE.${NC}"
    echo "Preserving existing configuration."
else
    # Check if a template exists in the source directory
    if [ -f "$SOURCE_CONF_FILE" ]; then
        echo "Found local configuration template. Installing..."
        cp "$SOURCE_CONF_FILE" "$DEST_CONF_FILE"
        echo -e "${GREEN}Installed configuration from $SOURCE_CONF_FILE${NC}"
    else
        echo "No local configuration template found. Starting interactive setup..."

        # Interactive Setup Fallback
        read -p "Enter full path to your access log [default: /var/log/nginx/concise.log]: " INPUT_LOG
        LOG_PATH=${INPUT_LOG:-/var/log/nginx/concise.log}

        read -p "Enter detection time window in seconds [default: 3000]: " INPUT_WINDOW
        TIME_WINDOW=${INPUT_WINDOW:-3000}

        cat <<EOF > "$DEST_CONF_FILE"
# Nginx Abuse Shield Configuration
# Generated by Installer on $(date)

LOG_FILES="$LOG_PATH $LOG_PATH.1"
TIME_WINDOW=$TIME_WINDOW
IP_PARTS=2
OUTPUT_FILE="$CONFIG_DIR/offending_ips.conf"
LOG_OUTPUT="/var/log/abuse-shield.log"

THRESH_IP_DIV=2
THRESH_3PART_NUM=2
THRESH_3PART_DEN=3
THRESH_2PART_NUM=5
THRESH_2PART_DEN=6
EOF
        echo -e "${GREEN}Generated default configuration at $DEST_CONF_FILE${NC}"
    fi
fi

# 6. Initialize Nginx Config Files (If missing)
touch "$CONFIG_DIR/offending_ips.conf"

if [ ! -f "$CONFIG_DIR/rate_limit_logic.conf" ]; then
    echo "Creating Nginx rate limit logic file..."
    cat <<EOF > "$CONFIG_DIR/rate_limit_logic.conf"
# Maps the remote address to the limit key found in the offending list
map \$remote_addr \$heavily_limited_ip_limit_key {
    include $CONFIG_DIR/offending_ips.conf;
    default "";
}

# Define the rate limit zone (1 request per 6 seconds)
limit_req_zone \$heavily_limited_ip_limit_key zone=heavily_limited_ip_rate_limit:50m rate=10r/m;

# Custom error page
limit_req_status 429;
error_page 429 @ratelimit;
EOF
fi

# 7. Setup Cron Job
echo "Setting up Cron Job..."
echo "*/15 * * * * root $INSTALL_DIR/save_offending_ips.sh >> /var/log/abuse-shield.log 2>&1" > "$CRON_FILE"
chmod 644 "$CRON_FILE"
echo -e "${GREEN}Cron job installed to $CRON_FILE${NC}"

# 8. Finished
echo "------------------------------------------------"
echo -e "${GREEN}SUCCESS!${NC}"
echo "1. Config file is located at: $DEST_CONF_FILE"
echo "2. Scripts are in: $INSTALL_DIR"
echo "3. Logs are in: /var/log/abuse-shield.log"
echo ""
echo "If this is a fresh install, remember to update your Nginx config to include:"
echo "   include $CONFIG_DIR/rate_limit_logic.conf;"
echo "------------------------------------------------"
